config/routes.rb
Rails.application.routes.draw do
  resources :consultations do
    resources :details, only: [:create, :destroy, :update]
  end
  resources :patients
  resources :specialties#, only: [:create, :destroy, :update, :index]
  resources :medics
  devise_for :doctors, controllers:{
    registrations: 'doctors/registrations'
  }

  resources :doctors, only: [:index, :show] do
    resources :medics, only: [:create]
  end
  get 'login_as/index'

  devise_for :admins, controllers:{
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers:{
    registrations: 'users/registrations'
  }
  resources :users, only: [:index, :show]

  root 'home#index'

end

app/controllers/login_as_controller.rb
class LoginAsController < ApplicationController
  def index
  end
end

app/helpers/login_as_helper.rb
module LoginAsHelper
end

app/views/login_as/index.html.erb
<div class="container">
  <h2>Login As:</h2>
  <div class="loginAs row between-xs">
    <div class="doctor row center-xs">
      <%= image_tag("doctor.jpg", :alt => "image", class: "img-circle col-xs-12")%>
      <%= link_to "Physician", new_doctor_session_path %>
    </div>
    <div class="secre row center-xs">
      <%= image_tag("secre.png", :alt => "image", class: "img-circle col-xs-12" ) %>
      <%= link_to "Secretary", new_user_session_path %>
    </div>
    <div class="admin row center-xs">
      <%= image_tag("admin.jpg", :alt => "image", class: "img-circle col-xs-12" ) %>
      <%= link_to "Administrator", new_admin_session_path %>
    </div>
  </div>
</div>