config/routes.rb
Rails.application.routes.draw do
  resources :consultations do
    resources :details, only: [:create, :destroy, :update]
  end
  resources :patients
  resources :specialties#, only: [:create, :destroy, :update, :index]
  resources :medics
  devise_for :doctors, controllers:{
    registrations: 'doctors/registrations'
  }

  resources :doctors, only: [:index, :show] do
    resources :medics, only: [:create]
  end
  get 'login_as/index'

  devise_for :admins, controllers:{
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers:{
    registrations: 'users/registrations'
  }
  resources :users, only: [:index, :show]

  root 'home#index'

end

app/models/consultation.rb
class Consultation < ActiveRecord::Base
  belongs_to :medic
  belongs_to :patient
  validates :patient_id, presence: true
  validates :medic_id, presence: true
  validates :time, presence: true
  validates :date, presence: true, :uniqueness => { :message => "and time of consultation is busy!"  }
  has_one :detail

end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController
  before_action :set_consultation, only: [:show, :edit, :update, :destroy]

  # GET /consultations
  # GET /consultations.json
  def index
    @consultations = Consultation.all
    @consultation = Consultation.new
  end

  # GET /consultations/1
  # GET /consultations/1.json
  def show
    @detail = Detail.new
  end

  # GET /consultations/new
  def new
    @consultation = Consultation.new
  end

  # GET /consultations/1/edit
  def edit
  end

  # POST /consultations
  # POST /consultations.json
  def create
    @consultation = Consultation.new(consultation_params)

    respond_to do |format|
      if @consultation.save
        format.html { redirect_to @consultation, notice: 'Consultation was successfully created.' }
        format.json { render :show, status: :created, location: @consultation }
      else
        format.html { render :new }
        format.json { render json: @consultation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consultations/1
  # PATCH/PUT /consultations/1.json
  def update
    respond_to do |format|
      if @consultation.update(consultation_params)
        format.html { redirect_to @consultation, notice: 'Consultation was successfully updated.' }
        format.json { render :show, status: :ok, location: @consultation }
      else
        format.html { render :edit }
        format.json { render json: @consultation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultations/1
  # DELETE /consultations/1.json
  def destroy
    @consultation.destroy
    respond_to do |format|
      format.html { redirect_to consultations_url, notice: 'Consultation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultation
      @consultation = Consultation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consultation_params
      params.require(:consultation).permit(:date, :time, :medic_id, :patient_id)
    end
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/views/consultations/_form.html.erb
      <% nameBtn ||= "Create Appointment"  %>
      <%= form_for @consultation do |f| %>
        <%= render "partials/fullMessages", objeto: @consultation %>
        <div class="row">
          <div class="col-md">
            <div class="field">
              <%= f.label :medic_id %>
              <%= f.select :medic_id , options_for_select(Medic.all.collect {|p| [p.doctor.first_name, p.id]}) %>
            </div>
            <div class="field">
              <%= f.label :patient_id %>
              <%= f.select :patient_id, options_for_select(Patient.all.collect {|p| [p.first_name, p.id]}) %>
            </div>
          </div>
          <div class="col-md">
            <div class="field">
              <%= f.label :date %>
              <div class='input-group date' id='datetimepicker1'>
                  <%= f.text_field :date, :required => true %>
                  <span class="input-group-addon">
                      <span class="glyphicon glyphicon-calendar"></span>
                  </span>
              </div>
            </div>
            <div class="field">
              <%= f.label :time %>
              <select name ="consultation[time]">
                <%hora = 8 %>
                <%13.times do %>
                  <option><%="#{hora}:00"  %></option>
                  <%hora = hora + 1 %>
                <%end %>
              </select>
            </div>
          </div>
        </div>




        <%= link_to (consultations_path) do %>
          <button type="button" class="btn btn-default">Go Back</button>
        <%end %>

        <%= f.submit nameBtn, class:"btn btn-primary"  %>

      <% end %>
    </div>

app/views/consultations/edit.html.erb
<div class="row middle-xs margen center-xs margen edit-consultation">
  <div class="edit-consultation-edit container-iniciar-form">
    <h2>Edit Appointment</h2>
    <%= render 'form', nameBtn: "Update" %>
  </div>
  <%= link_to 'Show', @consultation %>
</div>

app/views/consultations/index.html.erb
<div class="container">
  <section class="container-listado">
    <div class="container-all-listado">
      <h2>Appointment</h2>
      <p id="notice"><%= notice %></p>
      <hr>
      <table class="table table-striped container-all-listado-table">
        <thead>
          <tr>
            <th>#</th>
            <th>Patient</th>
            <th>Medic</th>
            <th>Date</th>
            <th>Time</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @consultations.each do |consultation| %>
            <tr>
              <td><%= consultation.id %></td>
              <td><%= consultation.patient.first_name %></td>
              <td><%= consultation.medic.doctor.first_name %></td>
              <td><%= consultation.date %></td>
              <td><%= consultation.time %></td>
              <td>
                <%= link_to (consultation), method: :delete, data: { confirm: 'Are you sure?' } do%>
                  <i class="fa fa-ban"></i>
                <%end %>
                <%= link_to (edit_consultation_path(consultation)) do %>
                  <i class="fa fa-pencil"></i>
                <%end %>
                <%= link_to (consultation) do %>
                  <i class="fa fa-eye" aria-hidden="true"></i>
                <%end %>

            </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
     <%= render "partials/modal" %>
  </section>
</div>

app/views/consultations/new.html.erb
<div class="row middle-xs margen center-xs margen edit-consultation">
  <div class="edit-consultation-edit container-iniciar-form">
    <h2>New consultation</h2>
    <%= render 'form'%>
  </div>
  <%= link_to 'Show', @consultation %>
</div>

app/views/consultations/show.html.erb
<div class="container">
  <div class="row middle-xs margen center-xs margen edit-consultation">
    <div class="edit-consultation-edit container-iniciar-form">
      <p id="notice"><%= notice %></p>
      <p>
        <strong>Patient:</strong>
        <%= @consultation.patient.first_name %><%= @consultation.patient.last_name %>
      </p>
      <p>
        <strong>Medic:</strong>
        <%= @consultation.medic.doctor.first_name %>
      </p>
      <p>
        <strong>Date:</strong>
        <%= @consultation.date %>
      </p>
      <p>
        <strong>Time:</strong>
        <%= @consultation.time %>
      </p>
      <%unless @consultation.detail.nil? %>
        <p>
          <strong>Reason:</strong>
          <%= @consultation.detail.reason %>
        </p>
        <p>
          <strong>Symptoms:</strong>
          <%= @consultation.detail.symptoms %>
        </p>
        <p>
          <strong>Diagnosis:</strong>
          <%= @consultation.detail.diagnosis %>
        </p>
        <p>
          <strong>Medicament:</strong>
          <%= @consultation.detail.medicament %>
        </p>
        <p>
          <strong>Total:</strong>
          $<%= @consultation.detail.total %>
        </p>
      <%end %>

      <%= link_to 'Edit', edit_consultation_path(@consultation) %> |
      <%= link_to 'Back', consultations_path %>
      <%if @consultation.detail.nil? %>
          <%= render "partials/modal", botnName: "Detail consultation", title:"#{@consultation.patient.first_name }'s consultation", ruta:"details/form"%>
      <%end %>
    </div>
  </div>
</div>