config/routes.rb
Rails.application.routes.draw do
  resources :consultations do
    resources :details, only: [:create, :destroy, :update]
  end
  resources :patients
  resources :specialties#, only: [:create, :destroy, :update, :index]
  resources :medics
  devise_for :doctors, controllers:{
    registrations: 'doctors/registrations'
  }

  resources :doctors, only: [:index, :show] do
    resources :medics, only: [:create]
  end
  get 'login_as/index'

  devise_for :admins, controllers:{
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers:{
    registrations: 'users/registrations'
  }
  resources :users, only: [:index, :show]

  root 'home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/consultation.rb
class Consultation < ActiveRecord::Base
  belongs_to :medic
  belongs_to :patient
  validates :patient_id, presence: true
  validates :medic_id, presence: true
  validates :time, presence: true
  validates :date, presence: true, :uniqueness => { :message => "and time of consultation is busy!"  }
  has_one :detail

end

app/models/detail.rb
class Detail < ActiveRecord::Base
  belongs_to :consultation
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 has_one :medic
end

app/models/medic.rb
class Medic < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :specialty
  validates :doctor_id, :uniqueness => { :message => "ya ha sido agregado!"  }
  validates :phone, presence: true
  validates :address, presence: true
  validates :specialty_id, presence: true
  has_many :consultations
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  validates :first_name, presence: true, length: { maximum: 20  }
  validates :last_name, presence: true, length: { maximum: 20  }
  validates :gender, presence: true
  validates :state, presence: true, length: { maximum: 20  }
  validates :city, presence: true, length: { maximum: 20  }
  validates :address, presence: true, length: { maximum: 20  }
  validates :cp, presence: true, length: { minimum: 5  }, length: { maximum: 5  }
  validates :email, presence: true, length: { maximum: 50  }
  validates :phone, presence: true, length: { maximum: 14  }
  has_many :consultations

  def self.search(search)
    where("first_name LIKE ?", "%#{search}%")
    where("last_name LIKE ?", "%#{search}%")
  end

end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
  validates :name, :presence => { :message => "es requerido!"  }
  validates :name, :uniqueness => { :message => "ya ha sido agregado!"  }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #validates :permission_level, :presence => { :message => "es requerido!"  }
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: [:show, :edit, :update, :destroy]

  # GET /details
  # GET /details.json
  def index
    @details = Detail.all
  end

  # GET /details/1
  # GET /details/1.json
  def show
  end

  # GET /details/new
  def new
    @detail = Detail.new
  end

  # GET /details/1/edit
  def edit
  end

  # POST /details
  # POST /details.json
  def create
    @detail = Detail.new(detail_params)

    respond_to do |format|
      if @detail.save
        format.html { redirect_to consultations_path, notice: 'Detail was successfully created.' }
        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /details/1
  # PATCH/PUT /details/1.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to @detail, notice: 'Detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail.destroy
    respond_to do |format|
      format.html { redirect_to details_url, notice: 'Detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail
      @detail = Detail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detail_params
      params.require(:detail).permit(:consultation_id, :reason, :symptoms, :diagnosis, :medicament, :total)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_admin!
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_doctor!, except: [:index, :show]
  def index
    @doctors = Doctor.all
  end
  def show
    @doctor = Doctor.find(params[:id])
    @medic = Medic.new
    @medics = Medic.all
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/medics_controller.rb
class MedicsController < ApplicationController
  before_action :authenticate_admin!, only: [:create, :update, :destroy]
  before_action :set_medic, only: [:show, :edit, :update, :destroy]

  # GET /medics
  # GET /medics.json
  def index
    @medics = Medic.all
  end

  # GET /medics/1
  # GET /medics/1.json
  def show
    @Medic = Medic.new
  end

  # GET /medics/new
  def new
    @medic = Medic.new
    @doctors = Doctor.all
  end

  # GET /medics/1/edit
  def edit
  end

  # POST /medics
  # POST /medics.json
  def create
    @medic = Medic.new(medic_params)

    respond_to do |format|
      if @medic.save
        format.html { redirect_to medics_path, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @medic }
      else
        format.html { redirect_to medics_path, alert: 'Doctor has already been created' }
        format.json { render json: @medic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medics/1
  # PATCH/PUT /medics/1.json
  def update
    respond_to do |format|
      if @medic.update(medic_params)
        format.html { redirect_to @medic, notice: 'Medic was successfully updated.' }
        format.json { render :show, status: :ok, location: @medic }
      else
        format.html { render :edit }
        format.json { render json: @medic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medics/1
  # DELETE /medics/1.json
  def destroy
    @medic.destroy
    respond_to do |format|
      format.html { redirect_to medics_path, notice: 'Medic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medic
      @medic = Medic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medic_params
      params.require(:medic).permit(:doctor_id, :specialty_id, :phone, :cell_phone, :address)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
  def show
    #code
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class=" alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_as_helper.rb
module LoginAsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BuenaSalud</title>
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Rationale' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <%= render "partials/header"  %>
  <%= render "partials/flashMessages"  %>
  <div class="main-container">
    <%= yield %>
  </div>
</body>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</html>

app/views/partials/_err404.html.erb
<div class="err404">
  <div class="margen row center-xs middle-xs" id="err404">
    <div>
      <div class="msj404">
        <h2><b>404</b></h2>
        <p>It looks like you found a</p>
        <h2>Dead Link</h2>
      </div>
      <div class="img404">
        <%= image_tag("link.png", :alt => "image" ) %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_flashMessages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/partials/_formSpecialty.html.erb
<div class="container">
  <section class="form-specialty row middle-xs center-xs" >
    <div>
      <% name ||= "New Specialty"  %>
      <% nameBtn ||= "Create"  %>
      <h2><%= name %></h2>
      <hr>
      <%= form_for(@specialty)  do |f| %>

        <div class="form-group">
          <label>Name</label>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <% @specialty.errors.full_messages.each do |message|  %>
          <div class="be_red white to-space">

            <div class="alert alert-danger">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
               <b><%= message  %></b>
            </div>
          </div>
        <%end %>
        <%= link_to (specialties_path) do %>
          <button type="button" class="btn btn-default">Go Back</button>
        <%end %>

        <%= f.submit nameBtn, class:"btn btn-primary"  %>

      <% end %>
    </div>
  </section>

</div>

app/views/partials/_fullMessages.html.erb
<% objeto ||= @patient %>
<% name ||= "patient" %>
<% if objeto.errors.any? %>
  <div id="error_explanation" class="alert alert-error fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <ul>
    <% objeto.errors.full_messages.each do |message| %>
      <li>*<%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_header.html.erb
<header class="header-home">
	<div class="row margen between-xs">
		<div class="col-xs-8 row margen middle-xs">
			<%= image_tag("logo.png", :alt => "image", class: "img-logo" ) %>
			<h1>Buena Salud</h1>
		</div>
		<% if user_signed_in?  %>
			<div class="header-user row middle-xs margen col-md end-xs">
				<i class="fa fa-user" aria-hidden="true"></i>
				<p><%= current_user.first_name%> <%= current_user.last_name%> (Secretary)</p>
			</div>
		<%elsif admin_signed_in?  %>
			<div class="header-user row middle-xs margen col-md end-xs">
				<i class="fa fa-user" aria-hidden="true"></i>
				<p><%= current_admin.first_name%> <%= current_admin.last_name%> (Administrator)</p>
			</div>
		<%elsif doctor_signed_in? %>
			<div class="header-user row middle-xs margen col-md end-xs">
				<i class="fa fa-user" aria-hidden="true"></i>
				<p><%= current_doctor.first_name%> <%= current_doctor.last_name%> (Doctor)</p>
			</div>
		<%end  %>
	</div>
	<nav class="header-home-nav">
		<%= render "partials/navItems" %>
	</nav>
</header>

app/views/partials/_indexAllUsers.html.erb
<% titulo ||= "Secretary" %>
<% table ||= @users  %>
<% enlace ||= new_user_registration_path %>
<% showUser ||= "secre" %>
<% btn ||= "New secretary" %>
<div class="container">
  <section class="container-listado">
      <div class="container-all-listado">
        <h2><%= titulo %></h2>
        <hr>
        <table class="table table-striped container-all-listado-table">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Last name</th>
              <th>Email</th>
              <th>Sign in count</th>
              <th>Update</th>
            </tr>
          </thead>
          <tbody>
            <% table.each do |field| %>
              <tr>
                <td><%= field.id  %></td>
                <td><%= field.first_name %></td>
                <td><%= field.last_name %></td>
                <td><%=field.email%></td>
                <td><%=field.sign_in_count %></td>
                <td><%=time_ago_in_words field.updated_at %> ago</td>
                <%if showUser != "secre"  %>
                  <td>
                    <%= link_to  field do %>
                      <i class="fa fa-info-circle" aria-hidden="true"></i>
                    <%end %>
                  </td>
                <%end %>
              </tr>
            <%end %>
          </tbody>
        </table>
      </div>
      <%= link_to (enlace) do  %>
        <button type="button" class="btn btn-primary" name="button"><%= btn %> </button>
      <%end %>
      <% if titulo != "Secretarias"  %>
        <%= link_to (medics_path) do  %>
          <button type="button" class="btn btn-default" name="button">Show information doctors </button>
        <%end %>
      <%end %>
  </section>

</div>

app/views/partials/_modal.html.erb
<% ruta ||= "form" %>
<% title ||= "New Appointment "%>
<% botnName ||= "New Appointment" %>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal"><%= botnName %></button>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= title %></h4>
      </div>
      <div class="modal-body">
        <%= render ruta %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_navItems.html.erb
<% if user_signed_in?  %>
  <% cerrar =  destroy_user_session_path %>
  <%  actualizar = edit_user_registration_path %>
<%elsif admin_signed_in? %>
  <% cerrar = destroy_admin_session_path %>
<%else %>
  <% cerrar = destroy_doctor_session_path %>
  <%actualizar = edit_doctor_registration_path %>
<%end %>
<ul class="row margen start-xs">
  <li class="col-xs-2  row margen center-xs"><%= link_to "Home", root_path, class:"nav-items" %></li>

  <% if user_signed_in? || admin_signed_in? || doctor_signed_in? %>
      <li class="col-md  row margen center-xs"><%= link_to "Appointments", consultations_path, class:"nav-items"  %></li>
      <li class="col-md  row margen center-xs"><%= link_to "Patients", patients_path, class:"nav-items"  %></li>
    <% if admin_signed_in? %>
      <li class="col-md  row margen center-xs"><%= link_to "Physicians Specialties", specialties_path, class:"nav-items"  %></li>
      <li class="col-md  row margen center-xs"><%= link_to "Physicians", doctors_path, class:"nav-items"  %></li>
      <li class="col-md  row margen center-xs"><%= link_to "Secretaries", users_path, class:"nav-items" %></li>
    <%elsif user_signed_in? %>
      <li class="col-md  row margen center-xs"><%= link_to "Physicians", medics_path, class:"nav-items"  %></li>
    <%end %>
    <% if doctor_signed_in? || user_signed_in? %>
      <li class="col-md  row margen center-xs"><%= link_to "Account Settings", actualizar, class:"nav-items" %></li>
    <%end %>
    <li class="col-md  row margen center-xs"><%= link_to "Log Out", cerrar, method: :delete, class:"nav-items" %></li>
  <%else %>
    <li class="col-xs-2  row margen center-xs"><%= link_to "Contact", root_path, class:"nav-items"  %></li>
    <li class="col-xs-2  row margen center-xs"><%= link_to "About", root_path, class:"nav-items"  %></li>
    <li class="col-xs-2  row margen center-xs"><%= link_to "Login As", login_as_index_path, class:"nav-items" %></li>
  <%end %>
</ul>