config/routes.rb
Rails.application.routes.draw do
  resources :consultations do
    resources :details, only: [:create, :destroy, :update]
  end
  resources :patients
  resources :specialties#, only: [:create, :destroy, :update, :index]
  resources :medics
  devise_for :doctors, controllers:{
    registrations: 'doctors/registrations'
  }

  resources :doctors, only: [:index, :show] do
    resources :medics, only: [:create]
  end
  get 'login_as/index'

  devise_for :admins, controllers:{
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers:{
    registrations: 'users/registrations'
  }
  resources :users, only: [:index, :show]

  root 'home#index'

end

app/models/detail.rb
class Detail < ActiveRecord::Base
  belongs_to :consultation
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: [:show, :edit, :update, :destroy]

  # GET /details
  # GET /details.json
  def index
    @details = Detail.all
  end

  # GET /details/1
  # GET /details/1.json
  def show
  end

  # GET /details/new
  def new
    @detail = Detail.new
  end

  # GET /details/1/edit
  def edit
  end

  # POST /details
  # POST /details.json
  def create
    @detail = Detail.new(detail_params)

    respond_to do |format|
      if @detail.save
        format.html { redirect_to consultations_path, notice: 'Detail was successfully created.' }
        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /details/1
  # PATCH/PUT /details/1.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to @detail, notice: 'Detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail.destroy
    respond_to do |format|
      format.html { redirect_to details_url, notice: 'Detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail
      @detail = Detail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detail_params
      params.require(:detail).permit(:consultation_id, :reason, :symptoms, :diagnosis, :medicament, :total)
    end
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_form.html.erb
<%= form_for([@consultation,@detail]) do |f| %>
  <div class="row">
    <div class="col-md">
      <div>
        <%= f.text_field :consultation_id, :value => @consultation.id,  autofocus: true, class:"input-id" %>
      </div>
      <div class="field">
        <%= f.label :reason %><br>
        <%= f.text_field :reason %>
      </div>
      <div class="field">
        <%= f.label :symptoms %><br>
        <%= f.text_field :symptoms %>
      </div>
    </div>
    <div class="col-md">
      <div class="field">
        <%= f.label :diagnosis %><br>
        <%= f.text_field :diagnosis %>
      </div>
      <div class="field">
        <%= f.label :medicament %><br>
        <%= f.text_field :medicament %>
      </div>
      <div class="field">
        <%= f.label :total %><br>
        <%= f.text_field :total %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Create", class:"btn btn-primary"%>
  </div>
<% end %>

app/views/details/edit.html.erb
<h1>Editing Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @detail %> |
<%= link_to 'Back', details_path %>

app/views/details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Details</h1>

<table>
  <thead>
    <tr>
      <th>Consultation</th>
      <th>Reason</th>
      <th>Symptoms</th>
      <th>Diagnosis</th>
      <th>Medicament</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @details.each do |detail| %>
      <tr>
        <td><%= detail.consultation %></td>
        <td><%= detail.reason %></td>
        <td><%= detail.symptoms %></td>
        <td><%= detail.diagnosis %></td>
        <td><%= detail.medicament %></td>
        <td><%= detail.total %></td>
        <td><%= link_to 'Show', detail %></td>
        <td><%= link_to 'Edit', edit_detail_path(detail) %></td>
        <td><%= link_to 'Destroy', detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Detail', new_detail_path %>

app/views/details/new.html.erb
<h1>New Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', details_path %>

app/views/details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Consultation:</strong>
  <%= @detail.consultation %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @detail.reason %>
</p>

<p>
  <strong>Symptoms:</strong>
  <%= @detail.symptoms %>
</p>

<p>
  <strong>Diagnosis:</strong>
  <%= @detail.diagnosis %>
</p>

<p>
  <strong>Medicament:</strong>
  <%= @detail.medicament %>
</p>

<p>
  <strong>Total:</strong>
  <%= @detail.total %>
</p>

<%= link_to 'Edit', edit_detail_path(@detail) %> |
<%= link_to 'Back', details_path %>